---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop
spec:
  type: NodePort
  selector:
    app: juice-shop
  ports:
  - name: http
    port: 80              # exposed inside the cluster
    targetPort: 3000      # container port
    nodePort: 30001       # choose an unused port (30000‑32767)