apiVersion: v1
kind: Service
metadata:
  name: juice-shop
spec:
  selector:
    app: juice-shop
  ports:
  - name: http
    port: 80          # Service port inside the cluster
    targetPort: 3000  # containerPort defined above