controller:
  service:
    type: ClusterIP
  ingressClass: nginx
  ingressClassResource:
    name: nginx
    enabled: true
  watchNamespace: ""
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  containerSecurityContext:
    runAsUser: null
    runAsGroup: null
    allowPrivilegeEscalation: false
    runAsNonRoot: true
  config: {}